### ISSUE TITLE
--post-append and memory use

### ISSUE THREAD

**Issue by edsu** [webrecorder/cdxj-indexer#17]
When indexing a large WARC file (89GB) with `--post-append` the cdxj-indexer process starts using all available memory on a machine with 8GB of memory. I don't know if this is something specific about this WARC file, or if it is a more general problem when indexing large WARC files. I can supply the WARC file if it helps in testing.

**Comment by edsu** [comment]
I was using `--sort` on an unusually large WARC file which sorts in memory. I fixed it by writing the CDXJ file without `--sort` and then using the `sort` unix utility to sort it.

    LC_ALL=C sort unsorted.cdxj > sorted.cdxj

**Comment by ikreymer** [comment]
Ah, thanks for clarifying! Yes, `--post-append` itself should not use much memory, but --sort unfortunately does. The native sort is definitely more efficient than the one here, perhaps something to optimize in the future.

**Comment by ikreymer** [comment]
This is actually important to solve from WACZ generation as well, unless we always call the external `sort` command.
But i'd like to get cdxj-indexer to be able to sort large files natively as well.
